### ISSUE TITLE
Checksum mismatch for php-pear-1.10.17-1.el8.remi.noarch in remi-php81

### ISSUE THREAD

**Issue by youdofoo** [remicollet/remirepo#329]
Hello,

I am encountering a checksum mismatch error when trying to download `php-pear-1.10.17-1.el8.remi.noarch` from the remi-php81 repository on EL8.
Here is the error message:
```
[MIRROR] php-pear-1.10.17-1.el8.remi.noarch.rpm: Downloading successful, but checksum doesn't match. 
Calculated: da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1(sha256)
Expected: 450c9d4172b14aeff568f84eb5eaef6b8d965bd2746e897b68d2f8705f14e58e(sha256)
```

Additional Context:
* This issue seems specific to the remi-php81 repository.
* I have checked remi-php80 and remi-php82, and the package downloads correctly without any checksum errors in those repositories.
* I have already tried `dnf clean all`, but the issue persists.

Could you please check the repository metadata or the package file integrity?

Thanks.

**Comment by remicollet** [comment]
Sorry, I cannot reproduce

```
# dnf install php-pear
Remi's RPM repository for Enterprise Linux 8 - x86_64                                                                                                         3.0 MB/s | 3.0 kB     00:00    
Remi's Modular repository for Enterprise Linux 8 - x86_64                                                                                                     3.4 MB/s | 3.5 kB     00:00    
Safe Remi's RPM repository for Enterprise Linux 8 - x86_64                                                                                                    3.0 MB/s | 3.0 kB     00:00    
Dependencies resolved.
==============================================================================================================================================================================================
 Package                                   Architecture                            Version                                                Repository                                     Size
==============================================================================================================================================================================================
Installing:
 php-pear                                  noarch                                  1:1.10.17-1.el8.remi                                   remi-modular                                  367 k

Transaction Summary
==============================================================================================================================================================================================
Install  1 Package

Total download size: 367 k
Installed size: 2.1 M
Is this ok [y/N]: y
Downloading Packages:
php-pear-1.10.17-1.el8.remi.noarch.rpm                                                                                                                        7.7 MB/s | 367 kB     00:00    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                         7.5 MB/s | 367 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                      1/1 
  Installing       : php-pear-1:1.10.17-1.el8.remi.noarch                                                                                                                                 1/1 
  Running scriptlet: php-pear-1:1.10.17-1.el8.remi.noarch                                                                                                                                 1/1 
  Verifying        : php-pear-1:1.10.17-1.el8.remi.noarch                                                                                                                                 1/1 
Installed products updated.

Installed:
  php-pear-1:1.10.17-1.el8.remi.noarch                                                                                                                                                        

Complete!
```

But repodata have been updated recently, can you please try again

Notice da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1 is the proper checsum

**Comment by youdofoo** [comment]
Thank you for your reply. I just tried again (after dnf clean all), but unfortunately, the issue persists.

The checksum mismatch appears to be specific to the `remi-php81` repository. (While `remi-modular` works fine, `remi-php81` seems to have inconsistent metadata.)

I compared the repository metadata against the actual remote file, confirming that the actual RPM file does not match the metadata.
* Checksum in metadata: `450c9d4172b14aeff568f84eb5eaef6b8d965bd2746e897b68d2f8705f14e58e`
  ```bash
  $ curl -sL http://rpms.remirepo.net/enterprise/8/php81/x86_64/repodata/00746ee58b7513900f6e6aee32097abb5dd96af6cd9c93aa5aed795307910718-primary.xml.bz2 | bzcat | grep "<name>php-pear</name>" -A 4 | grep "1.10.17" -C 2
  <name>php-pear</name>
  <arch>noarch</arch>
  <version epoch="1" ver="1.10.17" rel="1.el8.remi"/>
  <checksum type="sha256" pkgid="YES">450c9d4172b14aeff568f84eb5eaef6b8d965bd2746e897b68d2f8705f14e58e</checksum>
  <summary>PHP Extension and Application Repository framework</summary>
  ```
* Checksum of actual file: `da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1`
  ```bash
  $ curl -sL https://rpms.remirepo.net/enterprise/8/php81/x86_64/php-pear-1.10.17-1.el8.remi.noarch.rpm | sha256sum
  da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1  -
  ```

Reproduction using dnf:
```bash
# Create a temporary repo file pointing strictly to remi-php81
$ cat <<EOF > /etc/yum.repos.d/remi-php81-test.repo
[remi-php81-test]
name=remi-php81-test
baseurl=https://rpms.remirepo.net/enterprise/8/php81/x86_64/
enabled=1
gpgcheck=0
EOF

# Try to download the specific package
$ dnf download --disablerepo='*' --enablerepo='remi-php81-test' php-pear-1.10.17-1.el8.remi.noarch
```
Result:
```
remi-php81-test                                                                                                                                                       88 kB/s | 233 kB     00:02    
[MIRROR] php-pear-1.10.17-1.el8.remi.noarch.rpm: Downloading successful, but checksum doesn't match. Calculated: da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1(sha256)  Expected: 450c9d4172b14aeff568f84eb5eaef6b8d965bd2746e897b68d2f8705f14e58e(sha256) 
[MIRROR] php-pear-1.10.17-1.el8.remi.noarch.rpm: Downloading successful, but checksum doesn't match. Calculated: da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1(sha256)  Expected: 450c9d4172b14aeff568f84eb5eaef6b8d965bd2746e897b68d2f8705f14e58e(sha256) 
[MIRROR] php-pear-1.10.17-1.el8.remi.noarch.rpm: Downloading successful, but checksum doesn't match. Calculated: da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1(sha256)  Expected: 450c9d4172b14aeff568f84eb5eaef6b8d965bd2746e897b68d2f8705f14e58e(sha256) 
[MIRROR] php-pear-1.10.17-1.el8.remi.noarch.rpm: Downloading successful, but checksum doesn't match. Calculated: da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1(sha256)  Expected: 450c9d4172b14aeff568f84eb5eaef6b8d965bd2746e897b68d2f8705f14e58e(sha256) 
[FAILED] php-pear-1.10.17-1.el8.remi.noarch.rpm: No more mirrors to try - All mirrors were already tried without success  
```

I also confirmed that this issue occurs on aarch64.
Could you please trigger a metadata regeneration for `remi-php81`?

(Note: I encountered this issue while running `reposync` for a local mirror, which is currently blocked by this mismatch.)

**Comment by remicollet** [comment]
> The checksum mismatch appears to be specific to the remi-php81 repository. 

This is not designed to be used as a repository
Please only use remi-modular.


BTW, metadata will be regenerated shortly

**Comment by remicollet** [comment]
metadata were regenerated for most repo (php >= 8.1)

For context this is related to https://bugzilla.redhat.com/show_bug.cgi?id=2422995
and was fixed by https://git.remirepo.net/cgit/tools/helpers.git/commit/?id=b63f8c225c34318cbfc805dfe221ea3946d7d3cb

**Comment by youdofoo** [comment]
Thanks for the clarification. I misunderstood its intended usage. I will use only remi-modular from now on.

However, it seems the original issue persists. I am still getting the checksum mismatch error when trying to download the package from remi-php81.

I checked the regenerated metadata, and the checksum is still wrong.
```
$ curl -sL http://rpms.remirepo.net/enterprise/8/php81/x86_64/repodata/909eb1fd734ff5e3af4934a83d5bb44920f4f68b9626c0b2a103cb7042ec9056-primary.xml.bz2 | bzcat | grep "<name>php-pear</name>" -A 4 | grep "1.10.17" -C 2
  <name>php-pear</name>
  <arch>noarch</arch>
  <version epoch="1" ver="1.10.17" rel="1.el8.remi"/>
  <checksum type="sha256" pkgid="YES">450c9d4172b14aeff568f84eb5eaef6b8d965bd2746e897b68d2f8705f14e58e</checksum>
  <summary>PHP Extension and Application Repository framework</summary>
```

**Comment by remicollet** [comment]
Should be fixed now (createrepo cache issue)

```
$ curl -sL http://rpms.remirepo.net/enterprise/8/php81/x86_64/repodata/d6560d02e18c570deeacaf825ef28089fcc7d3d29f8793ebbba6cba790765cf9-primary.xml.bz2 | bzcat | grep "<name>php-pear</name>" -A 4 | grep "1.10.17" -C 2
  <name>php-pear</name>
  <arch>noarch</arch>
  <version epoch="1" ver="1.10.17" rel="1.el8.remi"/>
  <checksum type="sha256" pkgid="YES">da79425c77827f700531598bcffad02607ee4423240c0620fd86247e7fc309a1</checksum>
  <summary>PHP Extension and Application Repository framework</summary>

```

**Comment by youdofoo** [comment]
I confirmed the issue is resolved. Thank you for the quick update.
Closing this issue. Thanks again!
